<?php	
$data = array(
"titre"       => 'Signalement nouveau équidé (Origine inconnue)', 
"action"      => 'dashboard/create/',
"origine"     => 'oic',
"Datesigna"   => date('d-m-Y'),
"NomA"        => '',
"N"           => '',
"Dns"         => date('d-m-Y'),
"Race1"       => '1',
"Race2"       => 'Race',
"Robe1"       => '1',
"Robe2"       => 'Robe',
"NPPRODUIT"   => '',
"Pere"        => '',
"NPere"       => '',
"DnsPere"     => date('d-m-Y'),
"RacePere1"   => '1',
"RacePere2"   => 'Race Pere',
"CouleurPere1"=> '1',
"CouleurPere2"=> 'Robe',
"NPPERE"      => '',
"mere"        => '',
"NMere"       => '',
"DnsMere"     => date('d-m-Y'),
"RaceMere1"   => '1',
"RaceMere2"   => 'Race Mere',
"CouleurMere1"=> '1',
"CouleurMere2"=> 'Robe',
"NPMERE"      => '',
"ideleveur1"  => '1',
"ideleveur2"  => 'Proprietaire',
"Naisseur1"   => '1',
"Naisseur2"   => 'Naisseur',
"DateAprouve" => date('d-m-Y'),
"Origine1"    => 'DZ',
"Origine2"    => 'Algérie',
"Prix"        => '000000',
"Tete"        => '',
"AG"          => '',
"AD"          => '',
"PG"          => '',
"PD"          => '',
"MARQUES"     => ''
);
HTML::cheval($data);
?>